version: '3.9'
services:
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  auth:
    build:
      context: ./services/auth
      target: dev
    environment:
      - NODE_ENV=development
      - PORT=4010
      - CORS_ORIGIN=*
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_KEY_PREFIX=auth:
      - JWT_ACCESS_TOKEN_SECRET=dev-access-secret
      - JWT_REFRESH_TOKEN_SECRET=dev-refresh-secret
      - JWT_ACCESS_TTL_SECONDS=900
      - JWT_REFRESH_TTL_SECONDS=604800
      - OTP_CODE_TTL_SECONDS=300
      - OTP_MAX_REQUESTS_PER_HOUR=5
    volumes:
      - ./services/auth:/app
      - /app/node_modules
    ports:
      - '4010:4010'
    depends_on:
      - redis

volumes:
  redis-data: {}

