version: '3.9'
services:
  minio:
    image: quay.io/minio/minio:RELEASE.2025-01-20T01-00-02Z
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --address :9000 --console-address :9001
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data

  media:
    build:
      context: ./services/media
      target: dev
    environment:
      - NODE_ENV=development
      - PORT=4008
      - CORS_ORIGIN=*
      - S3_ENDPOINT=http://minio:9000
      - S3_REGION=us-east-1
      - S3_ACCESS_KEY_ID=minioadmin
      - S3_SECRET_ACCESS_KEY=minioadmin
      - S3_BUCKET=media
      - S3_FORCE_PATH_STYLE=true
    volumes:
      - ./services/media:/app
      - /app/node_modules
    ports:
      - '4008:4008'
    depends_on:
      - minio

  caddy:
    image: caddy:2.8.4-alpine
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    environment:
      - ACME_AGREE=true
    volumes:
      - ./ops/tls/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - media

volumes:
  minio-data: {}
  caddy-data: {}
  caddy-config: {}

