version: '3.9'
services:
  app:
    build:
      context: ./
      dockerfile: ./services/auth/Dockerfile
    image: app-backend:prod
    env_file:
      - ./ops/prod.env
    environment:
      - NODE_ENV=production
    ports:
      - "4000:4000"
    depends_on:
      - redis
  events:
    build:
      context: ./events_service
      dockerfile: Dockerfile
    image: events-service:prod
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
  search:
    build:
      context: ./agent9-search
      dockerfile: Dockerfile
    image: search-service:prod
    environment:
      - PORT=4100
    ports:
      - "4100:4100"
  media:
    build:
      context: ./services/media
      dockerfile: Dockerfile
    image: media-service:prod
    environment:
      - PORT=4500
    ports:
      - "4500:4500"
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./ops/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
