apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: traefik
  repo: https://traefik.github.io/charts
  targetNamespace: traefik
  set:
    ports.web.redirectTo: websecure
    ingressClass.enabled: true
    ingressClass.isDefaultClass: true
    providers.kubernetesIngress.ingressClass: traefik
    logs.general.level: INFO
