version: '3.8'
services:
  coturn:
    image: coturn/coturn:latest
    container_name: coturn
    network_mode: host
    restart: unless-stopped
    env_file:
      - .env
    command: >
      turnserver
      --no-cli
      --no-tls
      --listening-port=3478
      --realm=${TURN_REALM}
      --fingerprint
      --lt-cred-mech
      --user=${TURN_USERNAME}:${TURN_PASSWORD}
      --no-software-attribute
      --no-multicast-peers
      --no-tcp-relay
      --log-file=stdout
      --simple-log
      --external-ip=${EXTERNAL_IP}
      --min-port=49160 --max-port=49200

  typesense:
    image: typesense/typesense:0.25.2
    container_name: typesense
    restart: unless-stopped
    environment:
      - TYPESENSE_API_KEY=xyz
      - TYPESENSE_DATA_DIR=/data
    ports:
      - "8108:8108"
    volumes:
      - typesense-data:/data

  agent9-search:
    build:
      context: ../../agent9-search
    environment:
      - PORT=4009
      - TYPESENSE_HOST=typesense
      - TYPESENSE_PORT=8108
      - TYPESENSE_PROTOCOL=http
      - TYPESENSE_API_KEY=xyz
    depends_on:
      - typesense
    ports:
      - "4009:4009"

volumes:
  typesense-data:
