apiVersion: v1
kind: Service
metadata:
  name: {{ include "events-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "events-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "events-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.service.port }}
