{{- range $name, $svc := .Values.services }}
{{- if and $svc.enabled $svc.ingress.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "kasi-connect.fullname" $ }}-{{ $name }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ $svc.ingress.subdomain }}.{{ $.Values.ingress.domain }}`)
      kind: Rule
      services:
        - name: {{ include "kasi-connect.fullname" $ }}-{{ $name }}
          port: {{ $svc.port }}
  {{- if $.Values.ingress.tls.enabled }}
  tls:
    certResolver: {{ $.Values.ingress.tls.certResolver }}
  {{- end }}
---
{{- end }}
{{- end }}
