name: CI

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ feature/** ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install root deps
        run: npm ci || npm i

      - name: Lint
        run: npm run lint --if-present

      - name: Typecheck
        run: npm run typecheck --if-present || true

      - name: Build services
        run: |
          (cd services/auth && npm ci && npm run build)
          (cd services/media && npm ci && npm run build || true)
          (cd agent9-search && npm ci && npm run build)
          (cd agent7-messaging && npm ci && npm run build)
          (cd services/wallet && npm ci && npm run build)

      - name: Run unit/integration tests
        run: |
          (cd services/auth && npm test || true)
          (cd agent7-messaging && npm test || true)

  compose-smoke:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Start compose (cursor profile)
        run: |
          docker compose -f docker-compose.dev.yml --profile cursor up -d
          sleep 12

      - name: Run migrations
        run: |
          chmod +x scripts/migrate.sh moderation_service/scripts/migrate.sh
          ./scripts/migrate.sh || true
          ./moderation_service/scripts/migrate.sh || true

      - name: Smoke tests (shell + node)
        run: |
          chmod +x scripts/smoke.sh
          ./scripts/smoke.sh
          node scripts/smoke.mjs

      - name: Shutdown
        if: always()
        run: docker compose -f docker-compose.dev.yml down -v

      - name: Collect logs and smoke summary
        if: failure()
        run: |
          mkdir -p artifacts
          docker compose -f docker-compose.dev.yml logs > artifacts/docker-logs.txt 2>&1 || true
          cp scripts/smoke.json artifacts/smoke.json || true

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: compose-logs-and-smoke
          path: artifacts
name: CI

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ feature/** ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install root deps
        run: npm ci || npm i

      - name: Lint
        run: npm run lint --if-present

      - name: Typecheck
        run: npm run typecheck --if-present || true

      - name: Build services
        run: |
          (cd services/auth && npm ci && npm run build)
          (cd services/media && npm ci && npm run build || true)
          (cd agent9-search && npm ci && npm run build)
          (cd agent7-messaging && npm ci && npm run build)
          (cd services/wallet && npm ci && npm run build)

      - name: Start compose (cursor profile)
        run: |
          docker compose -f docker-compose.dev.yml --profile cursor up -d
          sleep 10

      - name: Smoke tests
        run: |
          chmod +x scripts/smoke.sh
          ./scripts/smoke.sh

      - name: Run unit/integration tests
        run: |
          (cd services/auth && npm test || true)
          (cd agent7-messaging && npm test || true)

      - name: Shutdown
        if: always()
        run: docker compose -f docker-compose.dev.yml down -v
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  node:
    name: Node - ${{ matrix.project }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - project: root
            path: .
            run_lint: true
          - project: backend
            path: backend
            run_lint: false
          - project: web-admin
            path: web-admin
            run_lint: false
          - project: agent7-messaging
            path: agent7-messaging
            run_lint: false
          - project: agent9-search
            path: agent9-search
            run_lint: false
          - project: media-service
            path: services/media
            run_lint: false
          - project: events-service
            path: events-service
            run_tests: false
            run_lint: false
    defaults:
      run:
        working-directory: ${{ matrix.path }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ${{ format('{0}/package-lock.json', matrix.path) }}
      - name: Install dependencies
        run: if [ -f package-lock.json ]; then npm ci --no-fund --no-audit; else npm install --no-fund --no-audit; fi
      - name: Lint
        if: ${{ matrix.run_lint != false }}
        run: npm run lint --if-present
      - name: Test
        if: ${{ matrix.run_tests != false }}
        run: npm test --if-present
      - name: Upload coverage (agent7-messaging)
        if: matrix.project == 'agent7-messaging'
        uses: actions/upload-artifact@v4
        with:
          name: agent7-coverage
          path: agent7-messaging/coverage
          if-no-files-found: ignore
      - name: Build
        run: npm run build --if-present
      - name: Typecheck (root only)
        if: matrix.project == 'root'
        run: npx tsc -p tsconfig.app.json --noEmit

  python:
    name: Python lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install dependencies (if requirements exist)
        run: |
          set -e
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f events_service/requirements.txt ]; then pip install -r events_service/requirements.txt; fi
          if [ -f moderation_service/requirements.txt ]; then pip install -r moderation_service/requirements.txt; fi
      - run: python -m pip install --upgrade pip ruff
      - name: Ruff check
        run: ruff check . --exclude node_modules --exclude dist --exclude .next --exclude build

  terraform:
    name: Terraform validate
    runs-on: ubuntu-latest
    if: hashFiles('infra/*.tf') != ''
    defaults:
      run:
        working-directory: infra
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init -backend=false -input=false
      - run: terraform validate