name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci || npm install
      - run: npm --prefix services/auth ci || npm --prefix services/auth install
      - run: npm --prefix services/messaging ci || npm --prefix services/messaging install
      - run: npm --prefix services/auth run build
      - run: npm --prefix services/messaging run build

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  web-admin:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web-admin
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: web-admin/package.json
      - run: npm install --no-fund --no-audit
      - run: npm run build
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: backend/package.json
      - run: npm install --no-fund --no-audit
      - run: npm run build